### PR TITLE
fix rendered content

### LINKED ISSUE #229: Rendered content ignores newlines in text/plain
The new feature introduced in #228 is great, but I think the rendered part is wrong when email is text/plain.
In such case, newlines should be converted to BRs.
Example of raw content:
```
Hello user
this is your reservation id: 12345

Thanks!
the staff
```

Expected rendered content: the same as the raw.
Current rendered content:
```
Hello user this is your reservation id: 12345 Thanks! the staff
```

### PR DESCRIPTION
**Pull request by ro0NL**
replaces #235, fixes #229

### CODE REVIEW

**Comment by ro0NL** [comment]
still in my case the feature is defeated. as text/html is an alternative part. Previewing plain/text is now the same as raw content (both preserve newlines).

So ideally we just always have these tabs maybe? also for the child parts.

**Comment by ro0NL** [comment]
if we merge message body + parts into 1 list, and then only render tabs for text/html, i think that's best. Previewing text/plain really doesnt make sense IMHO.

File: DataCollector/MessageDataCollector.php [hunk 1]
```diff
@@ -60,6 +60,8 @@ public function collect(Request $request, Response $response, \Exception $except
                     ];
 
                     foreach ($logger->getMessages() as $message) {
+                        ($userContentTypeProp = new \ReflectionProperty(\Swift_Message::class, 'userContentType'))->setAccessible(true);
```
Comment (stof) [inline DataCollector/MessageDataCollector.php]: Do we really need to use Reflection to access it ?

Comment (ro0NL) [reply DataCollector/MessageDataCollector.php]: I think so. It's available with `getContentType()` or in headers.. but only if you have no alternative parts; otherwise it becomes `multipart/alternative`.

Also the first boundary is not part of `message.children`. Im not aware of any further internals :)

**Comment by fabpot** [comment]
Thank you @ro0NL.
